### ISSUE TITLE
cpu_input_boost by sultanxda requires more configuration

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/LOS-plus-kernel#1]
After looking at the kernel code with a magnifier glass (lol), I realised that this kernel (as well as Smartpack) doesn't have cpu input boost enabled by default. While it may be enabled in the kernel defconfig, there requires to be further configuration, in the form of a sysfs node. 

I thought this was quite strange but I was not surprised mainly due to the poor CPU scaling without using hotplugs that offer 'touch boost' features. 

> /sys/kernel/cpu_input_boost/enabled

When set to 0, input boost capabilities is disabled. The user must enable this manually, or this may be done by the dev using some form of script or kernel tuning app. AFAIK, Kernel Adiutor doesn't support tuning this yet, but I may be able to provide a custom profile for people to use that can make use of the custom tuning function found in KA. 

**The problem with current method of touch boost**
The reason why I this has got my attention is because in my opinion, cpu boosting should be handled by a cpu boost driver. I don't really like the idea of having the hotplug handle this responsibility. We've seen issues with this where I've found that (most) interactive based governors don't respond well to the touch boost found in intelliplug (and therefore also lazyplug). 

**My approaches**
1. Kernel init script - Will need to avoid touching original init files, must deal with selinux (or change to permissive). I would say I'm kinda newbie to shell scripts, but I've played around with them before. 
2. Custom KA profile - Probably the easiest, will have to see if this works fine. Short-term workaround
3. Just use hotplug 'touch boost' - Not the best, but it works ^tm
This is just my 2 cents as I still need to research about this to provide the best possible solution. 

@sunilpaulmathew

**Comment by sunilpaulmathew** [comment]
@gsstudios 
Thank you for investigating and providing this much details. I thought it was all enabled and working fine. 
It could be ideal if Kernel Auditor will handle the driver. But till then, we probably need to stick with the custom profiles... 
Edit: to be honest, I'm really happy with the situation without stock cpu_boost (with/without cpu input boost enabled...)
